#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Aug 29 11:31:48 PET 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=LegendaryAtmosphere_v2.5.zip
enableShaders=false
