#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Sep 07 01:38:49 PET 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=0
shaderPack=09 - Mellow Shader v3.1.1.zip
