name = ""
version = "1.12.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cdd3b76b9821ae0ad27d23dd9931dc23626486eb002fdf20b6cd684575e71f6"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
