name = ""
version = "1.13.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b387746073d60cb3b0642c92db8cd93bad3cb6df2effeff72e77d20bd0e551d6"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
