#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Aug 08 15:24:58 PET 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=5
shaderPack=08-Mellow Shader v3.1.1.zip
