#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Sep 05 22:38:22 PET 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=09 - Mellow Shader v3.1.1.zip
