#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Sep 06 08:57:22 PET 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=0
shaderPack=09 - Mellow Shader v3.1.1.zip
