name = "2026UNI Lite"
version = "1.14.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5192b28b34e704ad6194a22887be915d5880b54db98263209e075f8e72fcade"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
