modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="meed"
version="8.0.6"
displayName="Moderately Enough Effect Descriptions"
logoFile="icon.png"
credits="Neon_Cranberries"
displayURL="https://www.curseforge.com/minecraft/mc-mods/moderately-enough-effect-descriptions-meed"
authors="Neon_Cranberries"
# The description text for the mod (multi line!) (#mandatory)
description='''
Adds over 500 effect descriptions from 100+ mods to Minecraft!
'''

[[dependencies.meed]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[47,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.meed]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"